package com.trustedtime.trusted_time

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.os.SystemClock
import androidx.work.*
import io.flutter.FlutterInjector
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.dart.DartExecutor
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.view.FlutterCallbackInformation
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.util.concurrent.TimeUnit

/** Main entry point for the TrustedTime Android plugin. */
class TrustedTimePlugin : FlutterPlugin, MethodChannel.MethodCallHandler {

    private lateinit var methodChannel: MethodChannel
    private lateinit var backgroundChannel: MethodChannel
    private lateinit var integrityChannel: EventChannel
    private lateinit var context: Context

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        context = binding.applicationContext

        methodChannel = MethodChannel(binding.binaryMessenger, "trusted_time/monotonic")
        methodChannel.setMethodCallHandler(this)

        backgroundChannel = MethodChannel(binding.binaryMessenger, "trusted_time/background")
        backgroundChannel.setMethodCallHandler(this)

        integrityChannel = EventChannel(binding.binaryMessenger, "trusted_time/integrity")
        integrityChannel.setStreamHandler(object : EventChannel.StreamHandler {
            override fun onListen(args: Any?, sink: EventChannel.EventSink) =
                IntegrityWatcher.attach(context, sink)
            override fun onCancel(args: Any?) = IntegrityWatcher.detach(context)
        })
    }

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "getUptimeMs" -> result.success(SystemClock.elapsedRealtime())
            "getBootId" -> {
                // /proc/sys/kernel/random/boot_id: a fresh, world-readable
                // UUID generated by the kernel on every boot. Null (not an
                // error) when unreadable — the Dart side fails closed on a
                // missing boot ID by treating the anchor as rebooted.
                result.success(
                    try {
                        java.io.File("/proc/sys/kernel/random/boot_id")
                            .readText().trim()
                            .takeIf { it.isNotEmpty() }
                    } catch (_: Exception) {
                        null
                    }
                )
            }
            "enableBackgroundSync" -> {
                val minutes = call.argument<Int>("intervalMinutes") ?: (24 * 60)
                scheduleBackgroundSync(minutes.toLong())
                result.success(null)
            }
            "setBackgroundCallbackHandle" -> {
                val handle = call.argument<Number>("handle")?.toLong()
                if (handle == null) {
                    result.error("INVALID_ARGS", "handle is required", null)
                    return
                }
                context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
                    .edit()
                    .putLong(KEY_HANDLE, handle)
                    .apply()
                result.success(null)
            }
            "notifyBackgroundComplete" -> {
                // The worker installs its own scoped handler on the headless
                // engine's binary messenger after Dart starts (see
                // [BackgroundSyncWorker.runHeadlessSync]); that handler is
                // what actually unblocks the worker. This branch only fires
                // on the foreground engine, where the call is a no-op so a
                // foreground TrustedTime.runBackgroundSync() invocation
                // cannot prematurely complete an in-flight background run.
                result.success(null)
            }
            "getBackgroundStopReason" ->
                respondWithBackgroundStopReason(context, result)
            else -> result.notImplemented()
        }
    }

    private fun scheduleBackgroundSync(intervalMinutes: Long) {
        // WorkManager rejects periodic intervals below its hard 15-minute
        // floor (PeriodicWorkRequest.MIN_PERIODIC_INTERVAL_MILLIS). The Dart
        // layer already clamps to this floor; re-clamp here so a direct
        // channel call (or a future caller) can never construct an
        // unschedulable request.
        val floorMinutes = PeriodicWorkRequest.MIN_PERIODIC_INTERVAL_MILLIS / 60_000L
        val minutes = maxOf(intervalMinutes, floorMinutes)
        val request = PeriodicWorkRequestBuilder<BackgroundSyncWorker>(minutes, TimeUnit.MINUTES)
            .setConstraints(Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build())
            .build()
        // UPDATE preserves the existing schedule's timing across app
        // launches, but WorkerUpdater returns NOT_APPLIED for any finished
        // WorkSpec state (only CANCELLED gets delete + re-enqueue). A
        // periodic WorkSpec reaches the terminal FAILED state when a
        // Throwable escapes doWork(), after which UPDATE silently never
        // revives the schedule — verified on-device (see issue qn1). Check
        // the current state first and fall back to CANCEL_AND_REENQUEUE
        // for finished states so enableBackgroundSync always resurrects a
        // dead schedule.
        val workManager = WorkManager.getInstance(context)
        val future = workManager.getWorkInfosForUniqueWork(WORK_NAME)
        future.addListener(
            {
                val policy = try {
                    val state = future.get().firstOrNull()?.state
                    if (state != null && state.isFinished) {
                        ExistingPeriodicWorkPolicy.CANCEL_AND_REENQUEUE
                    } else {
                        ExistingPeriodicWorkPolicy.UPDATE
                    }
                } catch (_: Exception) {
                    ExistingPeriodicWorkPolicy.UPDATE
                }
                workManager.enqueueUniquePeriodicWork(WORK_NAME, policy, request)
            },
            { runnable -> runnable.run() },
        )
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        methodChannel.setMethodCallHandler(null)
        backgroundChannel.setMethodCallHandler(null)
        IntegrityWatcher.detach(context)
    }

    companion object {
        internal const val PREFS = "trusted_time_prefs"
        internal const val KEY_HANDLE = "tt_bg_callback_handle"
        internal const val BG_CHANNEL = "trusted_time/background"
        internal const val WORK_NAME = "trusted_time_sync"
    }
}

/**
 * Answers `getBackgroundStopReason` with the unique periodic work's state
 * and [WorkInfo.getStopReason] — the reason the OS stopped the *previous*
 * run attempt (WorkManager 2.9+; the platform populates real stop reasons
 * on API 31+, earlier releases report STOP_REASON_NOT_STOPPED).
 *
 * Shared by the foreground plugin handler and the worker's scoped headless
 * handler: the worker replaces the plugin's handler on [BG_CHANNEL] for the
 * headless engine, so without the worker-side branch a background fire —
 * the caller that actually wants this diagnostic — would get
 * notImplemented. The WorkManager query completes asynchronously; the
 * listener hops to the main looper because [MethodChannel.Result] must be
 * invoked on the platform thread.
 */
private fun respondWithBackgroundStopReason(
    context: Context,
    result: MethodChannel.Result,
) {
    val future = WorkManager.getInstance(context)
        .getWorkInfosForUniqueWork(TrustedTimePlugin.WORK_NAME)
    future.addListener(
        {
            try {
                val info = future.get().firstOrNull()
                if (info == null) {
                    result.success(null)
                } else {
                    result.success(
                        mapOf(
                            "state" to info.state.name,
                            "stopReason" to info.stopReason,
                        ),
                    )
                }
            } catch (e: Exception) {
                result.error("STOP_REASON_UNAVAILABLE", e.message ?: e.toString(), null)
            }
        },
        { runnable -> Handler(Looper.getMainLooper()).post(runnable) },
    )
}

/**
 * Outcome of a headless background sync as reported by the Dart isolate
 * via `notifyBackgroundComplete`.
 *
 * Distinguishing retryable from permanent failures lets the worker return
 * `Result.failure()` for errors that would fail identically on every
 * attempt (e.g. an invalid config), ending the current interval's retry
 * chain while leaving the periodic schedule intact.
 */
private enum class SyncVerdict { SUCCESS, FAILED_RETRYABLE, FAILED_PERMANENT }

/**
 * Periodic worker that performs the actual anchor refresh.
 *
 * If the host app has registered a Dart callback via
 * `TrustedTime.registerBackgroundCallback`, this worker spins up a headless
 * [FlutterEngine], invokes that callback (which is expected to call
 * `TrustedTime.runBackgroundSync()`), and waits for completion via the
 * `trusted_time/background.notifyBackgroundComplete` method-channel call.
 *
 * If no callback is registered, the fire is a deliberate no-op: the
 * package performs no network activity of its own (all traffic is
 * strictly limited to the user-configured time sources reached through
 * the Dart callback), and the anchor is refreshed on the next foreground
 * launch instead.
 */
class BackgroundSyncWorker(ctx: Context, params: WorkerParameters) : CoroutineWorker(ctx, params) {

    override suspend fun doWork(): Result = try {
        val prefs = applicationContext.getSharedPreferences(
            TrustedTimePlugin.PREFS, Context.MODE_PRIVATE,
        )
        val handle = prefs.getLong(TrustedTimePlugin.KEY_HANDLE, 0L)
        val callbackInfo =
            if (handle == 0L) null
            else FlutterCallbackInformation.lookupCallbackInformation(handle)
        // No registered callback: succeed without doing anything so the
        // periodic schedule stays alive (a later launch may register the
        // callback) and no retry/backoff churn is triggered for a state
        // that only an app launch can change.
        if (callbackInfo == null) Result.success()
        else runHeadlessSync(callbackInfo)
    } catch (e: CancellationException) {
        // WorkManager cancelling the worker must propagate.
        throw e
    } catch (_: Throwable) {
        // Last-resort guard: a Throwable escaping doWork() marks the
        // periodic WorkSpec FAILED — a terminal state that permanently
        // kills the schedule (verified on-device; see issue qn1). The
        // inner handlers already convert Exceptions, but a java.lang.Error
        // (e.g. OOM during FlutterEngine spin-up) or a throw from
        // teardown in runHeadlessSync's finally block would still escape
        // without this. Ask for a retry with backoff instead.
        Result.retry()
    }

    private suspend fun runHeadlessSync(
        callbackInfo: FlutterCallbackInformation,
    ): Result {
        // The deferred carries the Dart isolate's verdict, not just a
        // boolean: SUCCESS, FAILED_RETRYABLE (transient — quorum/timeout;
        // WorkManager should re-attempt this interval with backoff), or
        // FAILED_PERMANENT (non-transient — e.g. invalid config; retrying
        // would fail identically, so give up on this interval and wait
        // for the next periodic fire).
        val deferred = CompletableDeferred<SyncVerdict>()
        // Captured outside the try so the finally can tear down whatever
        // was created even when initialization itself throws partway
        // (e.g. executeDartCallback failing after the engine exists).
        var engine: FlutterEngine? = null
        var workerChannel: MethodChannel? = null

        return try {
            // FlutterEngine creation, plugin/channel wiring, and
            // executeDartCallback must run on the main thread; once Dart is
            // running the awaited completion arrives via a channel callback
            // (also delivered on main) but the suspended wait itself runs on
            // the worker's default dispatcher to avoid pinning a 9-minute
            // budget to Main and contending with the host app's UI work.
            withContext(Dispatchers.Main) {
                val loader = FlutterInjector.instance().flutterLoader()
                loader.startInitialization(applicationContext)
                loader.ensureInitializationComplete(applicationContext, null)

                // The FlutterEngine constructor auto-registers the host
                // app's GeneratedPluginRegistrant onto this headless engine
                // (v2 embedding), so plugin channels — this plugin's
                // trusted_time/monotonic and flutter_secure_storage for
                // anchor persistence — are live before Dart starts.
                val headless = FlutterEngine(applicationContext)
                engine = headless
                // Install the completion handler directly on the headless
                // engine's binary messenger so a foreground engine running in
                // the same process cannot complete this worker's deferred
                // (each FlutterEngine has its own messenger). Setting this
                // handler after engine construction also replaces the one
                // installed by auto-registration for the same channel name.
                val channel = MethodChannel(
                    headless.dartExecutor.binaryMessenger,
                    TrustedTimePlugin.BG_CHANNEL,
                )
                workerChannel = channel
                channel.setMethodCallHandler { call, result ->
                    when (call.method) {
                        "notifyBackgroundComplete" -> {
                            val success = call.argument<Boolean>("success") ?: false
                            // Absent flag (older Dart side) defaults to retryable,
                            // preserving the previous always-retry behaviour.
                            val retryable = call.argument<Boolean>("retryable") ?: true
                            val verdict = when {
                                success -> SyncVerdict.SUCCESS
                                retryable -> SyncVerdict.FAILED_RETRYABLE
                                else -> SyncVerdict.FAILED_PERMANENT
                            }
                            // CompletableDeferred.complete returns false (rather than
                            // throwing) when the deferred has already been resolved,
                            // which makes duplicate notifyBackgroundComplete calls or
                            // a late call racing with teardown safe. complete()'s
                            // Boolean return value is discarded intentionally — only
                            // the first verdict counts; later signals are no-ops.
                            deferred.complete(verdict)
                            result.success(null)
                        }
                        // The headless Dart isolate queries the previous
                        // attempt's stop reason at the start of each fire;
                        // this handler shadows the plugin's on the headless
                        // engine, so the branch must exist here too.
                        "getBackgroundStopReason" ->
                            respondWithBackgroundStopReason(applicationContext, result)
                        else -> result.notImplemented()
                    }
                }
                val args = DartExecutor.DartCallback(
                    applicationContext.assets,
                    loader.findAppBundlePath(),
                    callbackInfo,
                )
                headless.dartExecutor.executeDartCallback(args)
            }

            // 9-minute budget leaves headroom inside WorkManager's
            // 10-minute default cap; tasks that exceed this are killed by
            // the OS. The wait runs off-main on the worker's coroutine
            // dispatcher (Dispatchers.Default by default for
            // CoroutineWorker), so a long Dart sync does not block Main.
            // A timeout (null) is a budget kill, not a Dart verdict, so it
            // stays retryable.
            when (withTimeoutOrNull(9 * 60 * 1000L) { deferred.await() }) {
                SyncVerdict.SUCCESS -> Result.success()
                SyncVerdict.FAILED_PERMANENT -> Result.failure()
                SyncVerdict.FAILED_RETRYABLE, null -> Result.retry()
            }
        } catch (e: CancellationException) {
            // Preserve cooperative cancellation: WorkManager cancelling
            // the worker must propagate, not be converted into a retry.
            // The finally below still tears the engine down (its
            // withContext is NonCancellable).
            throw e
        } catch (_: Throwable) {
            // Loader/engine/callback initialization failures land here.
            // Ask WorkManager to retry with backoff rather than letting
            // the throwable escape doWork (which would mark the periodic
            // WorkSpec FAILED and permanently kill the schedule).
            Result.retry()
        } finally {
            // Teardown must hop back to Main and complete even if the
            // worker is cancelled (e.g., WorkManager kills the run on the
            // 10-minute boundary) or initialization threw partway,
            // otherwise the FlutterEngine leaks.
            withContext(NonCancellable + Dispatchers.Main) {
                workerChannel?.setMethodCallHandler(null)
                engine?.destroy()
            }
        }
    }
}
