name: trusted_time
description: Tamper-proof, high-precision network time for Flutter. Anchored to hardware monotonic clocks to prevent system-time manipulation.
version: 1.2.0
homepage: https://github.com/Sahad2701/trusted_time
repository: https://github.com/Sahad2701/trusted_time
issue_tracker: https://github.com/Sahad2701/trusted_time/issues
documentation: https://pub.dev/documentation/trusted_time/latest/

topics:
  - time
  - ntp
  - security
  - anti-fraud
  - tamper-proof

environment:
  sdk: ^3.9.2
  flutter: '>=3.35.4'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  plugin_platform_interface: ^2.1.8
  ntp: ^2.0.0
  web: ^1.1.1
  flutter_web_plugins:
    sdk: flutter
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.trustedtime.trusted_time
        pluginClass: TrustedTimePlugin
      ios:
        pluginClass: TrustedTimePlugin
      macos:
        pluginClass: TrustedTimePlugin
      windows:
        pluginClass: TrustedTimePlugin
      linux:
        pluginClass: TrustedTimePlugin
      web:
        pluginClass: TrustedTimeWebPlugin
        fileName: trusted_time_web.dart

