#include "include/trusted_time/trusted_time_plugin.h"
#include <cstring>
#include <flutter_linux/flutter_linux.h>
#include <gtk/gtk.h>
#include <sys/utsname.h>

#include "trusted_time_plugin_private.h"

#define TRUSTED_TIME_PLUGIN(obj)                                               \
  (G_TYPE_CHECK_INSTANCE_CAST((obj), trusted_time_plugin_get_type(),           \
                              TrustedTimePlugin))

struct _TrustedTimePlugin {
  GObject parent_instance;
};

G_DEFINE_TYPE(TrustedTimePlugin, trusted_time_plugin, g_object_get_type())

// GObject lifecycle

static void trusted_time_plugin_dispose(GObject *object) {
  G_OBJECT_CLASS(trusted_time_plugin_parent_class)->dispose(object);
}

static void trusted_time_plugin_class_init(TrustedTimePluginClass *klass) {
  G_OBJECT_CLASS(klass)->dispose = trusted_time_plugin_dispose;
}

static void trusted_time_plugin_init(TrustedTimePlugin *self) {}

// Method channel handler

static void method_call_cb(FlMethodChannel *channel, FlMethodCall *method_call,
                           gpointer user_data) {
  g_autoptr(FlMethodResponse) response = nullptr;
  const gchar *method = fl_method_call_get_name(method_call);

  if (strcmp(method, "getPlatformVersion") == 0) {
    struct utsname uname_data = {};
    uname(&uname_data);
    g_autofree gchar *version = g_strdup_printf("Linux %s", uname_data.version);
    g_autoptr(FlValue) result = fl_value_new_string(version);
    response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));

  } else if (strcmp(method, "getUptimeMs") == 0) {
    // CLOCK_BOOTTIME is identical to CLOCK_MONOTONIC but also counts time
    // during which the system was suspended — essential for accurate uptime
    // tracking on laptops and embedded devices. Available since kernel 2.6.39,
    // which predates all supported Ubuntu LTS, Fedora, and Debian stable
    // releases.
    struct timespec ts;
    clock_gettime(CLOCK_BOOTTIME, &ts);
    int64_t uptimeMs =
        static_cast<int64_t>(ts.tv_sec) * 1000 + ts.tv_nsec / 1000000;
    g_autoptr(FlValue) result = fl_value_new_int(uptimeMs);
    response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));

  } else if (strcmp(method, "getBootId") == 0) {
    // /proc/sys/kernel/random/boot_id: a fresh, world-readable UUID
    // generated by the kernel on every boot. Null (not an error) when
    // unreadable — the Dart side fails closed on a missing boot ID by
    // treating the anchor as rebooted.
    g_autofree gchar *contents = nullptr;
    if (g_file_get_contents("/proc/sys/kernel/random/boot_id", &contents,
                            nullptr, nullptr) &&
        contents != nullptr) {
      g_strstrip(contents);
      if (*contents != '\0') {
        g_autoptr(FlValue) result = fl_value_new_string(contents);
        response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));
      }
    }
    if (response == nullptr) {
      response = FL_METHOD_RESPONSE(fl_method_success_response_new(nullptr));
    }

  } else if (strcmp(method, "enableBackgroundSync") == 0) {
    // Stubbed: Dart Timer.periodic handles scheduling on desktop where the
    // app process runs persistently. Native OS schedulers (systemd timers)
    // would require privileges this plugin does not hold.
    g_autoptr(FlValue) result = fl_value_new_bool(TRUE);
    response = FL_METHOD_RESPONSE(fl_method_success_response_new(result));

  } else {
    response = FL_METHOD_RESPONSE(fl_method_not_implemented_response_new());
  }

  fl_method_call_respond(method_call, response, nullptr);
}

// Exposed for unit testing (see trusted_time_plugin_private.h).
FlMethodResponse *get_platform_version() {
  struct utsname uname_data = {};
  uname(&uname_data);
  g_autofree gchar *version = g_strdup_printf("Linux %s", uname_data.version);
  g_autoptr(FlValue) result = fl_value_new_string(version);
  return FL_METHOD_RESPONSE(fl_method_success_response_new(result));
}

// Plugin registration

void trusted_time_plugin_register_with_registrar(FlPluginRegistrar *registrar) {
  TrustedTimePlugin *plugin = TRUSTED_TIME_PLUGIN(
      g_object_new(trusted_time_plugin_get_type(), nullptr));

  g_autoptr(FlStandardMethodCodec) codec = fl_standard_method_codec_new();

  // Monotonic clock channel.
  g_autoptr(FlMethodChannel) monotonic_channel =
      fl_method_channel_new(fl_plugin_registrar_get_messenger(registrar),
                            "trusted_time/monotonic", FL_METHOD_CODEC(codec));
  fl_method_channel_set_method_call_handler(
      monotonic_channel, method_call_cb, g_object_ref(plugin), g_object_unref);

  // Background sync channel (stub).
  g_autoptr(FlMethodChannel) bg_channel =
      fl_method_channel_new(fl_plugin_registrar_get_messenger(registrar),
                            "trusted_time/background", FL_METHOD_CODEC(codec));
  fl_method_channel_set_method_call_handler(
      bg_channel, method_call_cb, g_object_ref(plugin), g_object_unref);

  g_object_unref(plugin);
}